- kubic-salt-master-image/root/usr/local/bin/entrypoint.sh
salt-master starts quite some external programs at boot time to collect facts about the machine where it's running. Each external call leads python2 to issue a lot of close()s syscalls. The majority of these calls are issued against file descriptors that are invalid (they have never been opened). That leads to the creation of errored close()s, which are NULL syscalls. These NULL syscalls are particularly affected by the meltdown fixes.
This leads to situations where the 1st salt-master worker takes around 2 minutes to be ready to handle incoming requests.
With this patch we can limit the maximum number of file descriptors open per process. This limit the range over which python2 will issue the close()s calls, leading to less NULL syscalls.
With this patch in place the 1st salt-master …
> salt-master: mitigate impact of meltdown patches

- kubic-caasp-dex-image/kubic-caasp-dex-image.kiwi
- kubic-chartmuseum-image/kubic-chartmuseum-image.kiwi
- kubic-dnsmasq-nanny-image/kubic-dnsmasq-nanny-image.kiwi
- kubic-flannel-image/kubic-flannel-image.kiwi
- kubic-haproxy-image/kubic-haproxy-image.kiwi
- kubic-helm-tiller-image/kubic-helm-tiller-image.kiwi
- kubic-kube-dns-image/kubic-kube-dns-image.kiwi
- kubic-kube-dns-sidecar-image/kubic-kube-dns-sidecar-image.kiwi
- kubic-kubernetes-node-pause-image/kubic-kubernetes-node-pause-image.kiwi
- kubic-mariadb-image/kubic-mariadb-image.kiwi
- kubic-openldap-image/kubic-openldap-image.kiwi
- kubic-pv-recycler-node-image/kubic-pv-recycler-node-image.kiwi
- kubic-salt-api-image/kubic-salt-api-image.kiwi
- kubic-salt-master-image/kubic-salt-master-image.kiwi
- kubic-salt-minion-image/kubic-salt-minion-image.kiwi
- kubic-velum-development-image/kubic-velum-development-image.kiwi
- kubic-velum-image/kubic-velum-image.kiwi
Changing tag by a placeholder facilitates the usage of
replace_using_package_version obs service in buildtime mode so
before every build the %%TAG%% placeholder is replaced by a given
package version. This is handy in order to align the tag of an appliance
to its main application version.
> Change tag by %%TAG%% place holder

- heapster-image/heapster-image.kiwi.ini
Move here so this can get into V4 (prerequisite to k8s dashboard)
- update author to SUSE containers team
- remove nobody user/group
- bump version
> move heapster-image to kubic/caasp template

- openldap-image/openldap-image.kiwi.ini
For some unknown reason, `/etc/openldap/slapd.conf` was not being loaded by `slapd`. This forces the right configuration file for `slapd`.
https://bugzilla.suse.com/show_bug.cgi?id=1092495
bsc#1092495
> Force the right configuration file for slapd

- mariadb-image/mariadb-image.kiwi.ini
- mariadb-image/root/usr/local/bin/entrypoint.sh
With the envvar `MYSQLD_CONFIG` it's possible to set default mysqld
settings that will be written into `/etc/my.cnf.d` when the container
starts.
E.g. `MYSQLD_CONFIG="skip-networking;max_allowed_packet=16M"` will produce:
```
[mysqld]
skip-networking
max_allowed_packet=16M
```
Fixes: bsc#1095335
> Allow providing configuration settings using envvars

- openldap-image/root/usr/local/bin/entrypoint.sh
entrypoint.sh used the old path of slapd
> openldap-image: fix path of slapd in entrypoint.sh

- nginx-ingress-controller-image/nginx-ingress-controller-image.kiwi.ini
Nginx modules are shipped in separate packages in openSUSE Factory
and this change provides the following:
- nginx-module-brotli
- nginx-module-cookie-flag
- nginx-module-devel-kit
- nginx-module-http-auth-digest
- nginx-module-http-substitutions-filter
- nginx-module-modsecurity
- nginx-module-set-misc
- nginx-module-sticky-ng
- nginx-module-vts
> nginx-ingress: Add nginx modules

- default-http-backend-image/default-http-backend-image.kiwi.ini
The binary of default HTTP backend is called kubernetes-404-server,
not default-http-backend.
> default-http-backend: Fix binary name

- README.md
- caasp-dex-image/caasp-dex-image.kiwi.ini
- chartmuseum-image/chartmuseum-image.kiwi.ini
- cilium-image/cilium-image.kiwi.ini
- default-http-backend-image/default-http-backend-image.kiwi.ini
- dnsmasq-nanny-image/dnsmasq-nanny-image.kiwi.ini
- flannel-image/flannel-image.kiwi.ini
- haproxy-image/haproxy-image.kiwi.ini
- heapster-image/heapster-image.kiwi.ini
- helm-tiller-image/helm-tiller-image.kiwi.ini
- kube-dash-image/kube-dash-image.kiwi.ini
- kube-dns-image/kube-dns-image.kiwi.ini
- kube-dns-sidecar-image/kube-dns-sidecar-image.kiwi.ini
- kubernetes-node-pause-image/kubernetes-node-pause-image.kiwi.ini
- mariadb-image/mariadb-image.kiwi.ini
- nginx-ingress-controller-image/nginx-ingress-controller-image.kiwi.ini
- openldap-image/openldap-image.kiwi.ini
- pv-recycler-node-image/pv-recycler-node-image.kiwi.ini
- salt-api-image/salt-api-image.kiwi.ini
- salt-master-image/salt-master-image.kiwi.ini
- salt-minion-image/salt-minion-image.kiwi.ini
- velum-development-image/velum-development-image.kiwi.ini
- velum-image/velum-image.kiwi.ini
With this commit images will be tagged with three different tags:
```
* <name>:<short_version>
* <name>:<long_version>
* <name>:<long_version>-<release>
```
With change there will be at least a unique tag per build and a semi-stable tag, as the `short_version` is not expected to change within a distro release cycle.
>  Add additional tags for images

- cilium-image/cilium-image.kiwi.ini
It fixes kubic-cilium-image build for aarch64
> Include glibc-devel-32bit only on x86_64

- cilium-image/cilium-image.kiwi.ini
awk is used by cilium's init.sh
> cilium: add awk in cilium container image

- init-image/init-image.kiwi.ini
This change is to make sure all images follow the same naming criteria.
> Rename image files and tags to match other images criteria

- pre_checkin.sh
This commit makes pre_checkin.sh script to exit 0 if no new changelog
entries are found (when using --mkchanges flag). This way the CI does
not report a failre when it is executed having nothing new to commit
at OBS.
> Do not fail if no new change log entries are found

- pre_checkin.sh
Tag of the latest build of Tumbleweed changed from `current` to
`latest`.
> Update Tumbleweed base image reference

- hyperkube-image/hyperkube-image.kiwi.ini
- Fixes https://github.com/kubic-project/kubic-init/issues/178
new name should be hyperkube:vX.Y.Z
> Add 'v' in front of the tag version

- cilium-image/cilium-image.kiwi.ini
This change removes gcc from the package list (which is not needed,
because only llvm can be used for compiling BPF programs) and adds an
explanation why glibc-devel-32bit is installed.
> cilium: Clean up package list

- cilium-image/cilium-image.kiwi.ini
This series of commits brings multiple changes to Cilium image:
- `cilium-proxy` package which enables L7 network policies in Cilium
- labels and history for container, according to the guide https://en.opensuse.org/Building_derived_containers
- usage of additionalflags instead to OBS-AddTag
> cilium: Add cilium-proxy, labels, history and use additionalflags

- pre_checkin.sh
SLES image with the `latest` tag doesn't seem to exist anymore, so let's
specify the 15 SP1 version.
> pre_checkin: Specify the concrete version of SLES

- cilium-init-image/cilium-init-image.kiwi.ini
cilium-init is a script for initial pre-deployment operations which is
supposed to be used for init container for Cilium.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> cilium: Add cilium-init image

- cilium-operator-image/cilium-operator-image.kiwi.ini
cilium-operator is a separate package now.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> cilium-operator: Fix package name

- cilium-etcd-operator-image/cilium-etcd-operator-image.kiwi.ini
- cilium-image/cilium-image.kiwi.ini
- cilium-init-image/cilium-init-image.kiwi.ini
- cilium-operator-image/cilium-operator-image.kiwi.ini
This change adds the following labels which were missing:
* org.opensuse.reference
* org.openbuildservice.disturl
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> cilium: Add missing labels

- cilium-etcd-operator-image/cilium-etcd-operator-image.kiwi.ini
- cilium-image/cilium-image.kiwi.ini
- cilium-image/kubic-extra-bootstrap-packages
- cilium-init-image/cilium-init-image.kiwi.ini
- cilium-operator-image/cilium-operator-image.kiwi.ini
This change contains the following fixes for the Cilium image:
- Using `latest` as the tag and version strings as additional tags.
- Using _LABEL_PREFIX_ as the label prefix, which means consuming it
from pre_checkin.sh script.
- Remove extra bootsrap packages.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> cilium: Several fixes

- cilium-image/cilium-image.kiwi.ini
- cilium-init-image/cilium-init-image.kiwi.ini
- cilium-operator-image/cilium-operator-image.kiwi.ini
Without cilium building there is no point in attempting to build the image for it
> cilium: use the same ExclusiveArch as cilium.spec does
